[env:ESP32_C6_env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
upload_port = COM3
monitor_speed = 9600
build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ESP32_C6_env
lib_deps = 
	adafruit/Adafruit NeoPixel